require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb

Metrics/ClassLength:
  Exclude:
    - 'lib/aic.rb'
    - 'lib/aic_type.rb'
    - 'lib/aic_doc_type.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/presenters/asset_presenter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - app/services/file_set_replacement_service.rb
    - app/models/concerns/permissions/lakeshore_visibility.rb
    - app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/services/file_set_replacement_service.rb
    - app/models/concerns/permissions/lakeshore_visibility.rb
    - app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/PredicateName:
  Exclude:
    - 'app/presenters/asset_presenter.rb'
    - 'app/presenters/concerns/citi_presenter_behaviors.rb'
    - 'app/models/parameterized_relationships.rb'
    - 'app/forms/curation_concerns/generic_work_form.rb'

Style/FileName:
  Exclude:
    - 'config/initializers/active_fedora-noid.rb'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/Validation:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/**/*'

RSpec/AnyInstance:
  Exclude:
    - 'spec/**/*'
