class ResourcePresenter < Sufia::GenericFilePresenter
  self.terms = [
    :department,
    :comments,
    :location,
    :metadata,
    :publishing_context,
    :tags,
    :status,
    :contributor,
    :coverage,
    :creator,
    :date,
    :description,
    :format,
    :identifier,
    :language,
    :publisher,
    :relation,
    :rights,
    :source,
    :subject,
    :title,
    :resource_type,
    :described_by,
    :same_as,
    :pref_label
  ]
end
