# frozen_string_literal: true
# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include AcceptsUris
  include ::CurationConcerns::CollectionBehavior
  include Permissions

  self.indexer = CollectionIndexer

  property :publish_channels, predicate: AIC.publishChannel, class_name: "PublishChannel"

  property :collection_type, predicate: AIC.collectionType, multiple: false, class_name: "ListItem"

  accepts_uris_for :publish_channels, :collection_type
end
